options:
	p: &3&lWARPS &8‣


#Requires SKull and skBee

on load:
	set {head::warps::spawn} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzUxMTM3ZTExNDQzYThmYmIwNWZjZDNjY2MxYWY5YmQyMzAzOTE4ZjM1NDQ4MTg1ZTNlZDk2ZWYxODRkYSJ9fX0="
	set {head::warps::crates} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzYxYjI3OWUwMGYxOWQ5ZjY5YTcxMmY2NTYwNzY3Y2FlMGNmYTAyYzgzMTYwZDQ2YzdmNTBjNzUyNmY2Nzc2ZSJ9fX0="
	set {head::warps::pve} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWMyNDUzNzkwOTM1NDI1NjRlNWUxM2IwNjg2NTkzODFmYWQzMTk2MDQ2NzQyNWM5ODJjMmVhZTIwMjYzZjYwZCJ9fX0="
	set {head::warps::pvp} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTNhOTZjYzI5MDMxNTJlM2VlNTU4NDJhYmYyMzkxMzc5ODBhZmY3NjEwOTAwNGIzYmQ3YTVjODU0OGNlIn19fQ=="
	set {head::warps::mining} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2EzYmI4NWRlYzEzMjlmZTgyOWNjNmNkY2QzNGUxYmQ2MGVlODMyZjU3MjYyOTY1MWYxNGI1ZTE0NTU1ZGJiMSJ9fX0="
	set {head::warps::fishing} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Y0MDk0MmYzNjRmNmNiY2VmZmNmMTE1MTc5NjQxMDI4NmE0OGIxYWViYTc3MjQzZTIxODAyNmMwOWNkMSJ9fX0="
	set {head::warps::farming} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTI1YmMwZjBkYjRhZDMxMGFhOTZjMTc5ZDVlNmM3MzJhY2QyNjJkOTkyOTM5NDExN2QzZTQ0NTEzYWUwYzFmYyJ9fX0="
	set {head::warps::nowarp} to skull with value "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWZkMjQwMDAwMmFkOWZiYmJkMDA2Njk0MWViNWIxYTM4NGFiOWIwZTQ4YTE3OGVlOTZlNGQxMjlhNTIwODY1NCJ9fX0="


function warpGUI(p: player):
	set {_gui} to dropper inventory named "&3&lWARPS"
	set slot 0 of {_gui} to {head::warps::spawn} named "&e&lSPAWN" with lore "&7Click to teleport!"
	set slot 1 of {_gui} to {head::warps::crates} named "&6&lCRATES" with lore "&7Click to teleport!"
	set slot 2 of {_gui} to {head::warps::pve} named "&e&lPVE" with lore "&7Click to teleport!"
	set slot 3 of {_gui} to {head::warps::pvp} named "&6&lPVP" with lore "&7Click to teleport"
	set slot 4 of {_gui} to {head::warps::mining} named "&e&lMINING" with lore "&7Click to teleport!"
	set slot 5 of {_gui} to {head::warps::fishing} named "&6&lFISHING" with lore "&7Click to teleport!"
	set slot 6,7,8 of {_gui} to {head::warps::nowarp} named "&c&oComing Soon :)"
	open {_gui} to {_p}

command /warpsadmin [<text>] [<text>]:
	permission: op
	permission message: &cYou do not have permission to do this
	trigger:
		if arg-1 is "set":
			if arg-2 is set:
				if {warp::%arg-2%} isn't set:
					set {warp::%arg-2%} to player's location
					send "{@p} &fYou set warp &b%arg-2% &fto your location"
					
		if arg-1 is "delete":
			if arg-2 is set:
				if {warp::%arg-2%} is set:
					delete {warp::%arg-2%}
					send "{@p} &fYou deleted warp &b%arg-2%"
					
		if arg-1 is "list":
			send "{@p} &7List"
			wait 1 tick
			send "%{warp::*}%"
			
on inventory click:
	if name of event-inventory contains "&3&lWARPS":
		cancel event
		if event-slot = 0:
			send "{@p} &fTeleported you to &b&lSPAWN"
			teleport player to {warp::spawn}
			
		if event-slot = 1:
			send "{@p} &fTeleported you to warp &b&lCRATES"
			teleport player to {warp::crates}
			
		if event-slot = 2:
			send "{@p} &fTeleported you to warp &b&lPVE"
			teleport player to {warp::pve}
			
		if event-slot = 3:
			send "{@p} &fTeleported you to warp &b&lPVP"
			teleport player to {warp::pvp}
			
			
		if event-slot = 4:
			send "{@p} &fTeleported you to warp &b&lMINING"
			teleport player to {warp::mining}
			
		if event-slot = 5:
			send "{@p} &fTeleported you to warp &b&lFISHING"
			teleport player to {warp::fishing}
			
		if event-slot = 6,7 or 8:
			send "{@p} &fWarp doesn't exist"
			
		close player's inventory
			
			

on tab complete:
	event-string = "/warpsadmin"
	set tab completions for position 1 to "set", "delete" and "list"


on command "/warp":
	cancel event
	warpGUI(player)
	
on command "/warps":
	cancel event
	warpGUI(player)
	

	
	
	
	
